Add docs for Database Spec v1alpha1
opensergo/opensergo-specification pull request #40
Opened 2022-09-06 11:25 UTC by mlycore

Add zh-cn docs for OpenSergo Database Spec v1alpha1.

(English version TBD)

2022-09-06 11:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensergo/opensergo-specification?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensergo/opensergo-specification?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensergo/opensergo-specification?pullRequest=40) it.</sub>

2022-09-06 15:55 UTC, jnan806 requested changes

2022-09-06 15:55 UTC, jnan806 commented on specification/zh-Hans/database.md
> +kind: VirtualDatabasemetadata:
`metadata:` 没有换行 😃

2022-09-06 15:57 UTC, jnan806 requested changes

2022-09-06 15:57 UTC, jnan806 commented on specification/zh-Hans/database.md
> +kind: VirtualDatabasemetadata:
`kind`后面的`metadata:` 没有换行 😃

2022-09-07 01:20 UTC, sczyh30 commented
Could you please sign the CLA here: https://cla-assistant.io/opensergo/opensergo-specification?pullRequest=40

2022-09-07 01:59 UTC, mlycore commented on specification/zh-Hans/database.md
> +kind: VirtualDatabasemetadata:
> `kind`后面的`metadata:` 没有换行 😃

Thanks! Fixed !

2022-09-08 06:11 UTC, sczyh30 requested changes

2022-09-08 06:11 UTC, sczyh30 commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
metadata 换行

2022-09-08 06:11 UTC, sczyh30 commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
metadata 换行

2022-09-08 06:11 UTC, sczyh30 commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
metadata 换行

2022-09-08 06:11 UTC, sczyh30 commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
metadata 换行

2022-09-08 06:11 UTC, sczyh30 commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
metadata 换行

2022-09-08 06:11 UTC, sczyh30 commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
metadata 换行

2022-09-08 06:18 UTC, sczyh30 reviewed
一个建议：对于规则配置类的 CRD，可否统一以 Rule 结尾？比如读写分离是不是可以视为规则配置？社区可以一起讨论下

2022-09-08 06:23 UTC, mlycore commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
fixed

2022-09-08 06:23 UTC, mlycore commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
fixed

2022-09-08 06:23 UTC, mlycore commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
fixed

2022-09-08 06:23 UTC, mlycore commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
fixed

2022-09-08 06:23 UTC, mlycore commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
fixed

2022-09-08 06:23 UTC, mlycore commented on specification/zh-Hans/database-example.md
> +kind: VirtualDatabasemetadata:
fixed

2022-09-08 06:25 UTC, mlycore commented
> 可否统一以 Rule 结尾

比如 ReadWriteSplittingRule , ShardingRule 这样么？

2022-09-08 06:27 UTC, sczyh30 commented
> > 可否统一以 Rule 结尾
> 
> 比如 ReadWriteSplittingRule , ShardingRule 这样么？

是的，可以看看是否合适

2022-09-08 06:31 UTC, sczyh30 commented on specification/zh-Hans/database.md
> +  - staticStrategy: 表示采用静态读写分离规则
这里面具体会有哪些可配置项，可否帮忙展开描述下？

2022-09-08 06:32 UTC, mlycore commented
> > > 可否统一以 Rule 结尾
> > 
> > 
> > 比如 ReadWriteSplittingRule , ShardingRule 这样么？
> 
> 是的，可以看看是否合适

两个问题：
* 如果不加 Rule 的话，未来是否会出现需要同名配置的其他场景？
* 如果规则类加 Rule 的话，非 Rule 的配置都有哪些呢？

我自己的理解：
* CRD 本身即配置，如果要区分 Rule 类型，是不是在 spec 里标识就可以满足了，这样让该方面的治理都聚合在一个 CRD 的 spec 里

2022-09-08 06:34 UTC, mlycore commented on specification/zh-Hans/database.md
> +  - staticStrategy: 表示采用静态读写分离规则
> 这里面具体会有哪些可配置项，可否帮忙展开描述下？

get，我来丰富一下字段说明

2022-09-10 12:37 UTC, sczyh30 approved these changes

2022-09-10 12:38 UTC, merged

2022-09-10 12:39 UTC, sczyh30 commented
Nice work. Thanks for contributing!
每个规则的详细字段说明可以统一提 PR 来做补充哈